spring:
  datasource:
    #url: jdbc:mysql://localhost:${PORT}/${DB}
    #username: ${USERNAME}
    #password: ${PASSWORD}
    url: jdbc:mysql://mydb-instance.czsag8i8o5ll.ap-northeast-2.rds.amazonaws.com:3306/mydb-instance?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: admin
    password: qwer1234!A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret:
    key: ${JWT_SECRET_KEY}



